### ISSUE TITLE
Cannot find tab or anything after installing via "Install from URL"

### ISSUE THREAD

**Issue by Nevysha** [526christian/AI-Image-PromptGenerator#1]
Hi,

Thanks for sharing your work ! I wanted to give it a try but after installing with "Install from URL" in Automatic1111 webui I can't find where this extension is. (I restarted webui several times)

![Screenshot 2023-01-29 141354](https://user-images.githubusercontent.com/122687716/215328630-22b506fd-9c08-4ccd-a423-0eb061a37f82.png)

Regards

**Comment by 526christian** [comment]
Heya. This is a standalone script, so it won't work from within the A1111 UI.
