### ISSUE TITLE
AttributeError: module 'gradio' has no attribute 'Tab'. Did you mean: 'Tabs'?

### ISSUE THREAD

**Issue by sashaok123** [526christian/AI-Image-PromptGenerator#5]
Traceback (most recent call last):
  File "C:\AI\AI-Image-PromptGenerator\promptgen.py", line 112, in <module>
    main()
  File "C:\AI\AI-Image-PromptGenerator\promptgen.py", line 21, in main
    with gr.Tab("Generate"):
AttributeError: module 'gradio' has no attribute 'Tab'. Did you mean: 'Tabs'?
![image](https://user-images.githubusercontent.com/27728380/222623269-464c2092-642a-4114-905e-2de29e6fb057.png)

**Comment by 526christian** [comment]
Hm. Someone else with a Gradio-related AttributeError had it because the Gradio version they had installed was old. What Gradio version do you have?

**Comment by 526christian** [comment]
(archiving repo)
